### ISSUE TITLE
Should set layout direction appropriately

### ISSUE THREAD

**Issue by rosenpin** [delight-im/Android-Languages#2]
If for example, the user chooses Arabic/Hebrew etc. 
The setFromPreference method should also set layout direction

**Comment by ocram** [comment]
Thanks for pointing this out and for providing the fix, which has been merged here: https://github.com/delight-im/Android-Languages/pull/3

Please change your dependency to

```
compile 'com.github.delight-im:Android-Languages:228ab5da286cb8723e93c98e1a953cc7fb49a82b'
```

in order to try this and report back if it works :) Thank you!

**Comment by rosenpin** [comment]
I ended up using my fork
https://github.com/rosenpin/Android-Languages

Thanks a bunch for this library though.
Do you know if it would be possible to show only available languages in the language selection dialog?
As in, only languages that are available in the app resources?
